---
- name: Validate pg_* vars
  delegate_to: localhost
  run_once: true
  block:
    - name: Check that PostgreSQL vars have values if creating a database
      when: groups['database'] | length > 0
      ansible.builtin.assert:
        that:
          - postgresql_admin_username is defined and postgresql_admin_username | length
          - postgresql_admin_password is defined and postgresql_admin_password | length

    - name: Check that PostgreSQL vars for Automation Gateway values are set
      ansible.builtin.assert:
        that:
          - gateway_pg_host is defined and gateway_pg_host | length
          - gateway_pg_port is defined and gateway_pg_port | int > 0
          - gateway_pg_database is defined and gateway_pg_database | length
          - gateway_pg_username is defined and gateway_pg_username | length
          - gateway_pg_password is defined and gateway_pg_password | length

    - name: Check that PostgreSQL vars for Automation Controller values are set
      when: groups['automationcontroller'] | length > 0
      ansible.builtin.assert:
        that:
          - controller_pg_host is defined and controller_pg_host | length
          - controller_pg_port is defined and controller_pg_port | int > 0
          - controller_pg_database is defined and controller_pg_database | length
          - controller_pg_username is defined and controller_pg_username | length
          - controller_pg_password is defined and controller_pg_password | length

    - name: Check that PostgreSQL vars for Automation Hub values are set
      when: groups['automationhub'] | length > 0
      ansible.builtin.assert:
        that:
          - hub_pg_host is defined and hub_pg_host | length
          - hub_pg_port is defined and hub_pg_port | int > 0
          - hub_pg_database is defined and hub_pg_database | length
          - hub_pg_username is defined and hub_pg_username | length
          - hub_pg_password is defined and hub_pg_password | length

    - name: Check that PostgreSQL vars for Automation EDA Controller values are set
      when: groups['automationeda'] | length > 0
      ansible.builtin.assert:
        that:
          - eda_pg_host is defined and eda_pg_host | length
          - eda_pg_port is defined and eda_pg_port | int > 0
          - eda_pg_database is defined and eda_pg_database | length
          - eda_pg_username is defined and eda_pg_username | length
          - eda_pg_password is defined and eda_pg_password | length

  rescue:
    - name: Set var for user notification of pg_ vars
      ansible.builtin.set_fact:
        check_pg_vars: >-
          "One or more *_pg_* variables did not have a value.
          Please make sure all of the *_pg_* variables have values."

    - name: Clear host errors
      ansible.builtin.meta: clear_host_errors

- name: Perform non-aap installer managed database connectivity tests
  when: groups['database'] | length == 0
  block:
    - name: Automation Gateway Database Tests
      when: inventory_hostname in groups['automationgateway']
      block:
        - name: Verify Gateway connectivity to DB server / port
          register: gateway_db_connection
          ignore_errors: true
          changed_when: false
          ansible.builtin.command:
            cmd: "nc -zv {{ gateway_pg_host }} {{ gateway_pg_port }}"

        - name: Verify Gateway database credentials by trying to connect to db
          register: gateway_pgsql_test
          ignore_errors: true
          community.postgresql.postgresql_ping:
            db: "{{ gateway_pg_database }}"
            login_host: "{{ gateway_pg_host }}"
            login_user: "{{ gateway_pg_username }}"
            login_password: "{{ gateway_pg_password }}"
            port: "{{ gateway_pg_port }}"

    - name: Automation Controller Database Tests
      when: inventory_hostname in groups['automationcontroller']
      block:
        - name: Verify Contoller connectivity to DB server / port
          register: controller_db_connection
          ignore_errors: true
          changed_when: false
          ansible.builtin.command:
            cmd: "nc -zv {{ controller_pg_host }} {{ controller_pg_port }}"

        - name: Verify Controller database credentials by trying to connect to db
          register: controller_pgsql_test
          ignore_errors: true
          community.postgresql.postgresql_ping:
            db: "{{ controller_pg_database }}"
            login_host: "{{ controller_pg_host }}"
            login_user: "{{ controller_pg_username }}"
            login_password: "{{ controller_pg_password }}"
            port: "{{ controller_pg_port }}"

    - name: Automation Hub database Tests
      when: inventory_hostname in groups['automationhub']
      block:
        - name: Verify Hub connectivity to DB server / port
          register: hub_db_connection
          ignore_errors: true
          changed_when: false
          ansible.builtin.command:
            cmd: "nc -zv {{ hub_pg_host }} {{ hub_pg_port }}"

        - name: Verify HUB database credentials by trying to connect to db
          register: hub_pgsql_test
          ignore_errors: true
          community.postgresql.postgresql_ping:
            db: "{{ hub_pg_database }}"
            login_host: "{{ hub_pg_host }}"
            login_user: "{{ hub_pg_username }}"
            login_password: "{{ hub_pg_password }}"
            port: "{{ hub_pg_port }}"

        - name: Make sure the hstore extension is enabled for Automation Hub
          community.postgresql.postgresql_ext:
            name: 'hstore'
            db: "{{ hub_pg_database }}"
            login_host: "{{ hub_pg_host }}"
            login_user: "{{ hub_pg_username }}"
            login_password: "{{ hub_pg_password }}"
            port: "{{ hub_pg_port }}"
            state: 'present'
            register: hstore_install
            ignore_errors: true
            # enabling hstore requires postgresql-contrib to be installed
            # on the database server.  if it's not installed this task will fail.
            # We want to ignore the failure and continue with the remainder of the tests.
            # Since it's not an AAP installation managed database we cannot install
            # the required package.

    - name: EDA Controller Database Tests
      when: inventory_hostname in groups['automationeda']
      block:
        - name: Verify EDA connectivity to DB server / port
          ansible.builtin.command:
            cmd: "nc -zv {{ eda_pg_host }} {{ eda_pg_port }}"
          register: eda_db_connection
          ignore_errors: true
          changed_when: false

        - name: Verify EDA database credentials by trying to connect to db
          community.postgresql.postgresql_ping:
            db: "{{ eda_pg_database }}"
            login_host: "{{ eda_pg_host }}"
            login_user: "{{ eda_pg_username }}"
            login_password: "{{ eda_pg_password }}"
            port: "{{ eda_pg_port }}"
          register: eda_pgsql_test
          ignore_errors: true

- name: Additional Automation Hub tests
  when: inventory_hostname in groups['automationhub']
  block:
    - name: Check number of Automation Hub nodes in inventory
      ansible.builtin.set_fact:
        hub_clustered: >-
          {{ true if groups['automationhub'] | length > 1
            else
            false
          }}

    - name: Perform clustered Automation Hub tasks
      when: hub_clustered
      block:
        - name: Gather facts about Automation Hub servers
          ansible.builtin.setup:

        - name: Assertion that the hub shared data path is set
          failed_when: false
          register: hub_nfs_var_assertion_result
          ansible.builtin.assert:
            that:
              - hub_shared_data_path is defined

        - name: Check for shared mount on clustered Automation Hub
          ansible.builtin.set_fact:
            nfsmount_set: >-
              {{ true if ansible_mounts | selectattr('mount', 'defined') |
                selectattr('fstype', 'search', 'nfs') |
                selectattr('mount', 'equalto', hub_shared_data_path) | length == 1
                else
                false
              }}
...
