---
- name: Check for AAP directory in users home directory
  register: aap_stat
  ansible.builtin.stat:
    path: '~/aap'

- name: Set fact for RPM or Containerized
  ansible.builtin.set_fact:
    is_containerized: "{{ aap_stat['stat']['exists'] }}"

- name: Get user info to determine if local
  ansible.builtin.getent:
    database: passwd
    fail_key: false
    key: "{{ ansible_env['USER'] }}"
    service: sss

- name: Get umask
  register: umask_result
  changed_when: false
  ansible.builtin.command: 'umask'

- name: Get service facts
  ansible.builtin.service_facts:

- name: Get firewall information
  register: firewalld_info_result
  become: true
  ansible.posix.firewalld_info:
    active_zones: true

- name: Set fact for home, var, and root mounts
  ansible.builtin.set_fact:
    home_mount_size: "{{ ansible_mounts | selectattr('mount', 'equalto', '/home') | map(attribute='size_total') | join }}"
    var_mount_size: "{{ ansible_mounts | selectattr('mount', 'equalto', '/var') | map(attribute='size_total') | join }}"
    tmp_mount_size: "{{ ansible_mounts | selectattr('mount', 'equalto', '/tmp') | map(attribute='size_total') | join }}"
    root_mount_size: "{{ ansible_mounts | selectattr('mount', 'equalto', '/') | map(attribute='size_total') | join }}"

- name: Include tasks for RPM based installs
  when: is_containerized
  ansible.builtin.include_tasks: containerized.yml

- name: Include tasks for RPM based installs
  when: not is_containerized
  ansible.builtin.include_tasks: rpm.yml

- name: Include tasks to display results in output
  ansible.builtin.include_tasks: results.yml
...
