---
# Possibly template the results to stdout?
# - name: Render results and write to stdout
#   delegate_to: localhost
#   run_once: true
#   ansible.builtin.template:
#     src: results.j2
#     dest: /dev/stdout

- name: Display test results
  ansible.builtin.debug:
    var: aap_preinstall_checks_test_results

- name: Clustered Automation Hub mounts
  when:
    - groups['automationhub'] | length > 1
    - inventory_hostname in groups['automationhub']
  ansible.builtin.debug:
    var: nfsmount_set

- name: Delegate output to localhost
  delegate_to: localhost
  run_once: true
  block:
    - name: Display AAP installed db test results
      ansible.builtin.debug:
        msg: >-
          {{ check_pg_vars if check_pg_vars is defined
            else
            "All PostgreSQL related vars were set properly" }}

    - name: Explain test results output
      ansible.builtin.debug:
        msg:
          - "Review the test results for individual servers above."
          - "If firewalld is running and enabled and the default firewall 
            zone is not public you will want to set the *_firewall_zone
            variables in your inventory file."
          - "All servers in the cluster should have a minimum of 4 CPU cores."
          - "All servers in the cluster should have a minimum of 16 GB of RAM."
          - "If you are installing containerized AAP, the /home mount should
            be 20 GB minimum."
          - "If you are installing containerized AAP, you will need approximately
            10 GB of space allocated to /tmp for the installation.  If you do
            not have a /tmp mount then ensure you have plenty of free space on
            the / mount."
          - "If you are installing AAP from RPM, the /var mount should be
            20 GB minimum.  If you do not have a /var mount, then the extra 20 GB
            of storage should be assigned to your / mount."
          - "Regardless of containerized or RPM, to perform the installation,
            the umask should be 0022."
          - "For AAP installed from RPM, the AWX account should have it's
            umask set to 0022 permanently.  This would be set after the install."
          - "For containerized AAP, the installing user's UID should be greater
            than 500."
          - "There have been issues with the collection install portion of the
            installation.  Consider setting hub_seed_collections=false in your
            inventory file."
          - "If the nfsmount_set variable returns false on your Automation Hub
            servers, then you have more than one server defined in your
            [automationhub] group but have not mounted the required shared NFS
            storage."

- name: Display Receptor test results
  when: inventory_hostname in groups['automationcontroller']
  ansible.builtin.debug:
    var: controller_to_exec_receptor_results
...
